 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/faceapis", type: :request do
  # Faceapi. As you add validations to Faceapi, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Faceapi.create! valid_attributes
      get faceapis_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      faceapi = Faceapi.create! valid_attributes
      get faceapi_url(faceapi)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_faceapi_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      faceapi = Faceapi.create! valid_attributes
      get edit_faceapi_url(faceapi)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Faceapi" do
        expect {
          post faceapis_url, params: { faceapi: valid_attributes }
        }.to change(Faceapi, :count).by(1)
      end

      it "redirects to the created faceapi" do
        post faceapis_url, params: { faceapi: valid_attributes }
        expect(response).to redirect_to(faceapi_url(Faceapi.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Faceapi" do
        expect {
          post faceapis_url, params: { faceapi: invalid_attributes }
        }.to change(Faceapi, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post faceapis_url, params: { faceapi: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested faceapi" do
        faceapi = Faceapi.create! valid_attributes
        patch faceapi_url(faceapi), params: { faceapi: new_attributes }
        faceapi.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the faceapi" do
        faceapi = Faceapi.create! valid_attributes
        patch faceapi_url(faceapi), params: { faceapi: new_attributes }
        faceapi.reload
        expect(response).to redirect_to(faceapi_url(faceapi))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        faceapi = Faceapi.create! valid_attributes
        patch faceapi_url(faceapi), params: { faceapi: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested faceapi" do
      faceapi = Faceapi.create! valid_attributes
      expect {
        delete faceapi_url(faceapi)
      }.to change(Faceapi, :count).by(-1)
    end

    it "redirects to the faceapis list" do
      faceapi = Faceapi.create! valid_attributes
      delete faceapi_url(faceapi)
      expect(response).to redirect_to(faceapis_url)
    end
  end
end
