 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/trainbots", type: :request do
  # Trainbot. As you add validations to Trainbot, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Trainbot.create! valid_attributes
      get trainbots_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      trainbot = Trainbot.create! valid_attributes
      get trainbot_url(trainbot)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_trainbot_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      trainbot = Trainbot.create! valid_attributes
      get edit_trainbot_url(trainbot)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Trainbot" do
        expect {
          post trainbots_url, params: { trainbot: valid_attributes }
        }.to change(Trainbot, :count).by(1)
      end

      it "redirects to the created trainbot" do
        post trainbots_url, params: { trainbot: valid_attributes }
        expect(response).to redirect_to(trainbot_url(Trainbot.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Trainbot" do
        expect {
          post trainbots_url, params: { trainbot: invalid_attributes }
        }.to change(Trainbot, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post trainbots_url, params: { trainbot: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested trainbot" do
        trainbot = Trainbot.create! valid_attributes
        patch trainbot_url(trainbot), params: { trainbot: new_attributes }
        trainbot.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the trainbot" do
        trainbot = Trainbot.create! valid_attributes
        patch trainbot_url(trainbot), params: { trainbot: new_attributes }
        trainbot.reload
        expect(response).to redirect_to(trainbot_url(trainbot))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        trainbot = Trainbot.create! valid_attributes
        patch trainbot_url(trainbot), params: { trainbot: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested trainbot" do
      trainbot = Trainbot.create! valid_attributes
      expect {
        delete trainbot_url(trainbot)
      }.to change(Trainbot, :count).by(-1)
    end

    it "redirects to the trainbots list" do
      trainbot = Trainbot.create! valid_attributes
      delete trainbot_url(trainbot)
      expect(response).to redirect_to(trainbots_url)
    end
  end
end
